apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  timeouts:
    apply: 200s
    assert: 200s
    cleanup: 60s
    delete: 60s
    error: 180s
    exec: 120s
  # skipDelete: true
  failFast: true
  forceTerminationGracePeriod: 10s
