# permissions for end users to edit authenticationclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/managed-by: kustomize
  name: authenticationclass-editor-role
rules:
- apiGroups:
  - authentication.kubedoop.dev
  resources:
  - authenticationclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.kubedoop.dev
  resources:
  - authenticationclasses/status
  verbs:
  - get
