# permissions for end users to view s3connections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/managed-by: kustomize
  name: s3connection-viewer-role
rules:
- apiGroups:
  - s3.zncdata.dev
  resources:
  - s3connections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - s3.zncdata.dev
  resources:
  - s3connections/status
  verbs:
  - get
