apiVersion: s3.zncdata.dev/v1alpha1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/managed-by: kustomize
  name: s3bucket-sample
spec:
  bucketName: mybucket
  connection: s3connection-sample
